# Generated by Django 4.2.15 on 2024-08-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank='True', choices=[('work', 'Work'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('chore', 'Chore'), ('study', 'Study'), ('event', 'Event'), ('fitness', 'Fitness'), ('daily routine', 'Daily Routine'), ('other', 'Other')], max_length=50),
        ),
    ]
